# This vagrantfile creates a VM that is capable of running Fabric Workshop sample network


Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "fabric-workshop"
  config.vm.synced_folder "..", "/home/vagrant/fabric"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.name = "fabric-workshop"
    vb.cpus = 4
    vb.memory = 8192
  end

  config.vm.provision :shell, name: "essentials", path: "essentials.sh"
  config.vm.provision :shell, name: "docker", path: "docker.sh"
  config.vm.provision :shell, name: "jdk", path: "java.sh"
  config.vm.provision :shell, name: "nodeJs", path: "nodeJs.sh"
  config.vm.provision :shell, name: "fabric", path: "fabric.sh"
  config.vm.provision :shell, name: "limits", path: "limits.sh"
end